version: '3'

services:
  redis:
    image: docker.io/bitnami/redis:7.4
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 6379:6379

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
      
  backend:
    build:
      dockerfile: ./Dockerfile.backend
    ports:
      - 8480:8480
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - mysql

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb

volumes:
  mongo-data:
